### PR TITLE
Testing CircleCI

### PR DESCRIPTION
**Pull request by hhtong**

### CODE REVIEW

**Comment by boothby** [comment]
Can I break it simply by commenting here? :stuck_out_tongue:

**Comment by boothby** [comment]
Hmm, it's not running the tests on various platforms.

**Comment by hhtong** [comment]
I'm gonna give it a few minutes... 🤞

**Comment by arcondello** [comment]
It is running them, they just haven't been included in the GUI yet.

**Comment by boothby** [comment]
I pushed a commit to @hhtong's branch to see how deep this shadowban goes

**Comment by boothby** [comment]
What a dumpster fire.  I think I found a bug in CircleCI.

**Comment by boothby** [comment]
Steps:
1) Link your github to CircleCI under duress, not noticing that they actually give an option to not open your private repos
2) Revoke their permissions on the Github end ASAP to mitigate the damage
3) Haha, sucker! CircleCI won't interact with your PRs or releases now!
4) Link your github to CircleCI, this time without giving them access to private repos.
5) CircleCI now treats you with the same respect that it gives random users without CircleCI accounts

**Pull request closed without merging**
