### PR TITLE
Add clique cache mining and manipulation functions

### PR DESCRIPTION
**Pull request by boothby**
Addresses #213, allows clique embedding caches to be exported, imported, and merged.

### CODE REVIEW

**Comment by arcondello** [comment]
So far this looks great! I see it's still in progress, what's left?

**Comment by boothby** [comment]
docs and tests :)

**Comment by boothby** [comment]
@arcondello I'm done tinkering now

**Comment by arcondello** [comment]
One of the appveyor tests took 60min, while the others took ~5. I am wondering if there is a bug?

**Review by arcondello — APPROVED** [review]
Once everything is passing, LGTM

**Comment by boothby** [comment]
:/ everything went fine the second time around... but I increased logging in case it happens in the future.

**Pull request merged**
