### PR TITLE
Support py39

### PR DESCRIPTION
**Pull request by randomir**

### CODE REVIEW

**Comment by randomir** [comment]
Seems like `dwave-system` (`dwave.embedding`) _is required_ in `minorminer/tests/test_busclique.py`.

That's a problem because `dwave-system` requires `minorminer`, thus creating a cyclic dependency.

@boothby, thoughts? Extracting/replicating just the minimum required for testing here?

**Comment by boothby** [comment]
Should be resolved by #149 but that's currently on a (far) back burner.  Is this a priority for you?

**Comment by randomir** [comment]
Yup, pretty high. It's blocking a release of new Ocean with python 3.9 support.

How about we move those busclique tests to dwave-system, until #149 is implemented? (If minorminer is the core dependency of dwave-system, it makes sense to test integration of dwave-system with minorminer in the higher-level package.)

**Comment by boothby** [comment]
#149 is resolved

**Comment by randomir** [comment]
Thanks @boothby!

**Pull request merged**
